'use strict';

module.exports = {

	ASTEROIDS_COUNT:				10,

	PLAYER_ACCELERATION:			400,
	PLAYER_MAX_VELOCITY:			400,
	PLAYER_ANGULAR_VELOCITY_LEFT:	-500,
	PLAYER_ANGULAR_VELOCITY_RIGHT:	500,
	PLAYER_BULLET_LIFESPAN:			800

};